-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: Kiana Realty Growth Platform
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Kiana Realty Growth Platform Schema
-- Description: Auto-generated database schema for Kiana Realty Growth Platform. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: Kiana Realty Growth Platform Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id INTEGER,
  lead_source VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE leads IS 'Schema: Kiana Realty Growth Platform Schema - Entity: Leads';

CREATE TABLE IF NOT EXISTS workflows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id INTEGER,
  status VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE workflows IS 'Schema: Kiana Realty Growth Platform Schema - Entity: Workflows';

CREATE TABLE IF NOT EXISTS activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id INTEGER,
  action VARCHAR(255),
  timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE activity_log IS 'Schema: Kiana Realty Growth Platform Schema - Entity: Activity_log';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO users (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO leads (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO workflows (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO activity_log (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
